"""empty message

Revision ID: 7722febf67a8
Revises: cc53bbac21af
Create Date: 2022-02-14 06:52:45.088196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7722febf67a8'
down_revision = 'cc53bbac21af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
